# Copyright <2022> Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# Adapted from https://github.com/marketplace/actions/remove-artifacts (available under MIT license)

name: Remove Old Artifacts

on: workflow_dispatch

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      actions: write

    steps:
      - name: Delete artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const response = await github.rest.actions.listArtifactsForRepo({
              owner,
              repo,
              per_page: 100,
            });
            
            const currentTime = new Date().getTime();
            const oneWeekInMs = 7 * 24 * 60 * 60 * 1000;
            
            for (const artifact of response.data.artifacts) {
              const createdAt = new Date(artifact.created_at).getTime();
              const ageInMs = currentTime - createdAt;
            
              if (ageInMs > oneWeekInMs) {
                console.log(`Deleting artifact ${artifact.name} (ID: ${artifact.id})`);
                await github.rest.actions.deleteArtifact({
                  owner,
                  repo,
                  artifact_id: artifact.id,
                });
              }
            }
